//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace blog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class post_comment
    {
        public long id { get; set; }
        public long postId { get; set; }
        public Nullable<long> parentId { get; set; }
        public string title { get; set; }
        public Nullable<byte> published { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
        public Nullable<System.DateTime> publishedAt { get; set; }
        public string contenido { get; set; }
    
        public virtual post post { get; set; }
    }
}
