//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace blog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class post_tag
    {
        public long id { get; set; }
        public long postId { get; set; }
        public long tagId { get; set; }
    
        public virtual post post { get; set; }
        public virtual tag tag { get; set; }
    }
}
